### ISSUE TITLE
Feat:email verification while sign up

### ISSUE THREAD

**Issue by Amnyadav** [sakeel-103/DFS-BFS-Graph-Travers#224]
As i see there is no email verification during sign up process. It will lead to creation of fake users .
Anyone can create account by anyone's email .

What I can do?
 I will implement a OTP based feature for email verification 
During sign up user gets a 6 digit OTP in email and after email verification user proceed to login page.

I will write the OTP generation api with proper testing and you can use them to implement this OTP based feature.

@sakeel-103 assign me this backend task of writing apis

**Comment by sakeel-103** [comment]
@Amnyadav 
In this project, when a user signs up, the data is currently stored in local storage. Please integrate a database like MongoDB or any other and connect it to the backend server. The user data should be stored in the backend database upon signup, instead of local storage. And then, implement the required features that you have raised
Then this feature will work efficiently.

**Comment by Amnyadav** [comment]
@sakeel-103 okii got it
