### ISSUE TITLE
[Important] Remove pages from website which are added just to take points

### ISSUE THREAD

**Issue by mehul-m-prajapati** [sakeel-103/DFS-BFS-Graph-Travers#387]
**Description**

- I have identified that our website includes several pages that appear to be added primarily to accumulate GSSoC points rather than provide valuable content or functionality. 
- This clutters the site and can negatively impact user experience and SEO.

**Tasks:**

**Identify Pages:**
- Compile a list of pages that seem to exist solely for point accumulation. Criteria may include pages with minimal content, repetitive information, or no significant user engagement.

**Review and Approval:**
- Present the scraped data to the admin for validation. Obtain approval for the removal of the identified pages.

**Remove Pages:**
Once approved, proceed to delete the unnecessary pages from the website.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
will you please, provide that pages which are useless on the website.

**Comment by mehul-m-prajapati** [comment]
@sakeel-103 :  I will give you list of pages here. 
- I see you that you have merged last 5 PRs which have level3. Those are redundant pages. These guys will do anything to get points. Please carefully look at the issues before merging.

**Comment by sakeel-103** [comment]
@mehul-m-prajapati 
Ok, then please provide those pages in the form of video, then I will assign will this to you.
Thank You.

**Comment by shubhagarwal1** [comment]
Hey @mehul-m-prajapati 
I’d like to clarify that all the pages I’ve contributed to the website are meaningful and designed to add value to the platform. If you have any specific concerns, I encourage you to review each page for its functionality and content before making assumptions. 

Instead of making baseless accusations, I suggest that a thorough review of all recent contributions across the repository would be more productive. Pointing fingers without proper investigation creates unnecessary conflict and fosters an unhealthy competitive environment. Let’s maintain a fair and collaborative space by focusing on constructive feedback and quality checks rather than personal biases.

Please stop this behaviour
@sakeel-103 please look into this matter

**Comment by mehul-m-prajapati** [comment]
@shubhagarwal1 :
I appreciate your perspective, but I want to emphasize that the goal of GSSoC is to enhance our project meaningfully. While I recognize that contributions come from a place of enthusiasm, it's essential to ensure that each addition genuinely improves our platform's usability and value.

Constructive feedback is vital for growth, and it’s crucial that we maintain a focus on quality to foster a positive and productive environment for all contributors.

Let’s collaborate on setting clear guidelines for contributions that align with our project's vision. This approach will support all developers, especially beginners, by helping them understand how to create impactful content.

Thank you for your understanding.

**Comment by shubhagarwal1** [comment]
@mehul-m-prajapati,
I appreciate your emphasis on the importance of meaningful contributions to GSSoC, and I agree that our shared goal should be to enhance the project’s usability and value. However, I want to clarify that my contributions have been made with that intent in mind.

In light of your comments to @sakeel-103 about the last five PRs being redundant, I would appreciate it if you could specifically point out any pages I created that you consider duplicates. It’s crucial that we approach these discussions constructively, rather than inadvertently misleading project admins or contributors based on a narrow view of what constitutes meaningful contributions.

Additionally, I’ve noticed several repositories that seem to be exhibiting favoritism. Why aren’t these issues being addressed? Why have you not added you views to that till not, the screenshot shared is from the last two days, and it shows that one individual is being assigned the majority of issues. Does this align with open-source guidelines? I think it’s worth reconsidering these practices to ensure that all contributors, especially beginners, have the opportunity to excel in their own ways, please do not do this on personal basis.

Let’s foster a humble and supportive environment that benefits everyone involved, allowing all contributors to learn and grow.

<img width="518" alt="Screenshot 2024-10-22 at 7 25 03 AM" src="https://github.com/user-attachments/assets/9ca4518b-39de-44d4-9d9a-ac8bc2d95689">

@sakeel-103

**Comment by shubhagarwal1** [comment]
@mehul-m-prajapati 
As you have mentionned to sakeel please tell, which page is redundant and not related to the website 
These were your words right, how my contributions are not aliged to the application, please elaborate, 

![Screenshot 2024-10-22 at 7 34 01 AM](https://github.com/user-attachments/assets/15b1780b-1ca5-428d-8b4e-58f61af19c1c)

List of pages i have added to the website 
Profile Page
PR #383 - Merged 18 hours ago

Searchable Algorithm Page
PR #382 - Merged 18 hours ago

Historical Events Page (covering various insights about DFS/BFS)
PR #381 - Merged 18 hours ago

Roadmap Page
PR #380 - Merged 18 hours ago

Algorithm Compare Page
PR #379 - Merged 19 hours ago

Page 404
PR #327 - Merged 3 days ago

Review and Questions Page
PR #290 - Merged 4 days ago

Editors Page
PR #269 - Merged 5 days ago

Git Contributors Page
PR #238 - Merged last week

Resource Page
PR #218 - Merged last week

Navbar for FAQ Page
PR #201 - Merged last week

Practice Page
PR #189 - Merged last week

Real World Page
PR #188 - Merged last week

Interactive Quiz Page
PR #187 - Merged last week

Code Efficiency Improvements and Refactoring
PR #151 - Merged last week

CICD Workflow for Automatic Issue Labeling
PR #137 - Merged last week

Common Navbar Component Across the Application
PR #124 - Merged 2 weeks ago

Dropdown on Profile Button (BFS and DFS Page)
PR #115 - Merged 2 weeks ago

Pass Viewer
PR #114 - Merged 2 weeks ago

FAQ Page
PR #113 - Merged 2 weeks ago

Git Logo on the Landing Page
PR #107 - Merged 2 weeks ago

Revamped Landing Page
PR #106 - Merged 2 weeks ago

Revamped BFS and DFS Page (removed inconsistent buttons)
PR #92 - Merged 2 weeks ago

Revamped Main Index Page
PR #90 - Merged 2 weeks ago

Toaster on the Logging Page (improving user interactivity)
PR #89 - Merged 2 weeks ago

**Comment by mehul-m-prajapati** [comment]
- You have got feedback earlier from Mastan:

![d1](https://github.com/user-attachments/assets/d2d52437-4ffa-49f8-a01c-1fe11020b3bb)

---

- Your earlier work seems fine. But, spamming 6-7 issues/PRs altogether creates doubt regarding intent. Also, it creates leftover merge conflicts which is there in master branch
![d2](https://github.com/user-attachments/assets/159bc378-0a38-4399-acc3-daf0f261115d)


- These things make other contributors hard to add new changes.

**Comment by mehul-m-prajapati** [comment]
![d1](https://github.com/user-attachments/assets/fed80a65-c824-45ae-a654-a610c57ffd8f)
- You have got feedback from Mastan earlier.
- Creating 6-7 issues/PR altogether creates a mess and leftover merge conflicts in master branch

![d2](https://github.com/user-attachments/assets/2e2e0453-a226-4618-a884-b8fa74a7a75f)

**Comment by shubhagarwal1** [comment]
@mehul-m-prajapati above nowhere defines spamming or the accusation you have raised to @sakeel-103 
please stop this, also if you have read that carefully i have defined my reason for creating the issue that way, which is understansdble, hope this works

**Comment by mehul-m-prajapati** [comment]
- Good Luck for future endeavors.

**Comment by shubhagarwal1** [comment]
> * Good Luck for future endeavors.

@mehul-m-prajapati you too, please donot report until you get verified on want you are complaining about

**Comment by shubhagarwal1** [comment]
> > * Good Luck for future endeavors.
> 
> @mehul-m-prajapati you too, please donot report until you get verified on want you are complaining about

**Comment by shubhagarwal1** [comment]
> ![d1](https://private-user-images.githubusercontent.com/7879392/378656246-fed80a65-c824-45ae-a654-a610c57ffd8f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjQ5NDAsIm5iZiI6MTcyOTU2NDY0MCwicGF0aCI6Ii83ODc5MzkyLzM3ODY1NjI0Ni1mZWQ4MGE2NS1jODI0LTQ1YWUtYTY1NC1hNjEwYzU3ZmZkOGYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMDIzNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTlkNzlkYmM4Yjc4YjYwMWI3Nzg0NWNiMGE0ODM3ODY4YzJiNTFjMjI4YTY5NDgzYzc4NmQ1YWIzNzA5MTA1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UK34S6E7DUGW2WvhSfwYiBarEVVRCTKpg9T5CP9zK0A)
> 
> * You have got feedback from Mastan earlier.
> * Creating 6-7 issues/PRs simultaneously creates a mess and leaves behind merge conflicts in the master branch, making it difficult for new contributors to add changes.
> 
> ![d2](https://private-user-images.githubusercontent.com/7879392/378656249-2e2e0453-a226-4618-a884-b8fa74a7a75f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjQ5NDAsIm5iZiI6MTcyOTU2NDY0MCwicGF0aCI6Ii83ODc5MzkyLzM3ODY1NjI0OS0yZTJlMDQ1My1hMjI2LTQ2MTgtYTg4NC1iOGZhNzRhN2E3NWYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMDIzNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNjY2M1ZDg4ZWEyNWI5YzI0ZmI2NDAwMWQ5OWMxMmRmMzYyYzdmNDU4MWJjODVjYzE0ZmUzNjZlMjY0OWI1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8Z7-iIamYKnmKaVQzCvnYwarmHSYYx-DIdF0lT4mAC4)

All my PRs are individual, and I make a conscious effort not to add changes to the same files that others are working on in order to maintain a clean code history. I find it frustrating that these unfounded allegations keep resurfacing, especially when the previous concerns were clarified and addressed and the issue you raised was completely pointless, why are you not pointing to the repos that really are spammig, like ezyshop etc..

**Comment by sakeel-103** [comment]
## Request Message to all contributors ##
I sincerely appreciate the enthusiasm and effort all contributors have put into this project. However, I’d like to gently remind everyone that GSSoC promotes a respectful, collaborative, and positive environment. Personal disputes or accusatory comments can disrupt team harmony and conflict with our guidelines.
Let's all focus on providing constructive feedback and collaborating to improve the project. Contributions should align with the project's goals, and if there are concerns about any PRs, they should be addressed respectfully and with a focus on finding solutions, rather than engaging in unproductive arguments. 

Note :- If any contributor is found engaging in such behavior, appropriate action will be taken against them.

Thank You !
