### ISSUE TITLE
Fixing Bugs and Adding new Features

### ISSUE THREAD

**Issue by Dhvani365** [sakeel-103/DFS-BFS-Graph-Travers#93]
Bugs:
1. Statement is wrongly formed:
![image](https://github.com/user-attachments/assets/2252738f-4086-4e64-98fc-ec8a1c4e4606)
2. Once logged in successfully. After going back from login page again allows to enter the website. Session should be expired once back button is clicked.
3. Actually login and register is not actually required for just visualizing DFS and BFS traversal.

Features:
1. Provide Responsiveness.
2. Add more algorithms like "A*", and visualize other DSA Problems.

What I can Do:
- As front end development enthusiast, I can help you with responsiveness and fixing the bugs. 
- As Data structure and Algorithms enthusiast, I can also incorporate other algorithms of DSA to scale the project.

If you find these changes necessary, please provide required assignments and labels so that I can start working on it after your confirmation.

Thank You!

**Comment by sakeel-103** [comment]
@Dhvani365 
I apologize for this. obviously, you are saying right but it doesn’t matter whether the login/signup form is required or not, but I used it in this project. and I stored the data in local storage. so, it would be better to connect the form to MongoDB or another database for data storage rather than relying on local storage.
